server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

  cloud:
    consul:
      host: 192.168.0.107
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        port: ${server.port}
        ip-address: ${spring.cloud.client.ip-address}
        prefer-ip-address: true